pages:
  image: node:22
  stage: deploy
  variables:
    VITE_BASE_PATH: "/love/"
  script:
    - npm ci
    - npm run build
  pages:
    publish: dist
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
